import json,pathlib
p=pathlib.Path(__file__).resolve().parent
(p/'dist').mkdir(exist_ok=True)
categories=['Fundamentos','Entrada e saída','Limpeza e transformação','Exploração e gráficos','Machine learning','Validação e métricas','PCA e clustering','Automação','Python e SQL','IA generativa','Receitas','Solução de problemas']
data=[]
def add(cat,name,desc,steps,tip,tags=''):
 data.append(dict(id=len(data)+1,cat=cat,name=name,desc=desc,steps=steps,tip=tip,tags=tags))
def batch(cat, rows):
 for r in rows:add(cat,*r)
batch('Fundamentos',[
('Workflow','Uma sequência visual de nós conectados que transforma dados em resultados.','Crie um workflow; adicione uma fonte de dados; conecte nós; configure e execute em ordem.','Anote objetivo, entrada e saída para facilitar a manutenção.','fluxo pipeline início'),
('Estados dos nós','O estado indica se o nó precisa de configuração, está pronto ou foi executado.','Vermelho: não configurado. Amarelo: configurado. Verde: executado. Inspecione mensagens de aviso e erro.','As representações visuais podem variar entre interfaces e versões.','semáforo erro'),
('Portas e conexões','Nós podem transportar tabelas, modelos, variáveis e outros objetos.','Conecte portas compatíveis; consulte a documentação do nó para saber o tipo esperado.','Um modelo treinado e uma tabela de teste entram em portas diferentes do Predictor.','port model'),
('Configurar, executar e resetar','Configurar define parâmetros; executar calcula saídas; resetar descarta o resultado.','Abra a configuração; selecione colunas; execute; inspecione a tabela de saída.','Alterar um nó pode exigir a reexecução dos nós posteriores.','execute reset'),
('Repositório e extensões','Encontre nós pelo nome em inglês e instale integrações quando necessário.','Busque o nome; leia a descrição; confira entradas, saídas e extensão necessária.','Nós ausentes podem depender de extensão ou ter substitutos em versões recentes.','install hub'),
('Component vs. Metanode','Ambos organizam grupos de nós; componentes permitem encapsular configuração e interfaces reutilizáveis.','Agrupe etapas relacionadas; use Component para reutilização e configuração; Metanode para organização local.','Prefira interfaces de entrada e saída simples.','componente'),
('Flow variables','Valores que controlam configurações dos nós durante a execução.','Crie uma variável; conecte a porta de variáveis; associe-a ao parâmetro na configuração.','Nome e tipo da variável precisam ser compatíveis com o parâmetro.','variáveis parâmetros'),
('Documentação do workflow','Rótulos e anotações tornam o fluxo compreensível.','Nomeie blocos: entrada, limpeza, modelagem e avaliação; registre hipóteses e decisões.','Inclua origem dos dados, semente aleatória e critério de seleção do modelo.','boas práticas')])
batch('Entrada e saída',[
('CSV Reader','Importa arquivos CSV e outros textos delimitados.','Confira caminho, separador, cabeçalho, aspas, encoding e tipos de coluna.','Vírgula decimal e ponto e vírgula como separador são comuns em bases brasileiras.','importar leitura'),
('Excel Reader','Lê planilhas e intervalos de arquivos Excel.','Selecione o arquivo, a aba, a linha de cabeçalho e o intervalo.','Colunas com números misturados a texto podem ser importadas como string.','xlsx'),
('Table Creator','Cria uma pequena tabela manual para testes.','Defina nomes e tipos de coluna; preencha algumas linhas; execute.','Use dados pequenos para testar uma regra antes de processar toda a base.','manual'),
('List Files/Folders','Lista arquivos para processamento em lote.','Selecione a pasta; filtre extensão; use os caminhos em um loop de leitura.','Ordene e valide a lista antes de combinar arquivos.','pasta batch'),
('CSV Writer / Excel Writer','Exporta tabelas para arquivos externos.','Escolha destino; configure sobrescrita, cabeçalho e formato; execute.','Confirme o conteúdo exportado e evite sobrescrever a base original.','exportar salvar'),
('Table Reader / Table Writer','Lê e grava tabelas no formato de tabela do KNIME.','Use para persistir resultados intermediários ou transportar tabelas entre fluxos.','Formato de tabela preserva tipos melhor que CSV.','persistência'),
('GET Request / JSON Path','Obtém dados de APIs e extrai campos de JSON.','Configure URL, cabeçalhos e autenticação; valide status; extraia campos e expanda listas.','Respeite paginação, limites da API e tratamento de respostas vazias.','api rest json')])
batch('Limpeza e transformação',[
('Column Filter','Mantém ou remove colunas.','Selecione atributos úteis; remova IDs sem significado preditivo e colunas redundantes.','Não deixe o alvo ou atributos derivados dele entrarem nas features.','colunas seleção'),
('Row Filter / Rule-based Row Filter','Filtra linhas por valor, intervalo ou condição.','Defina coluna e critério; confira quantidade de linhas antes e depois.','Filtros excessivos podem alterar a distribuição da população.','linhas'),
('Missing Value','Trata valores ausentes por estratégias por tipo ou coluna.','Escolha média, mediana, valor fixo ou outra estratégia adequada; inspecione a saída.','Para avaliação de ML, estime parâmetros de imputação apenas no treino.','faltantes nulos'),
('Duplicate Row Filter','Remove ou identifica registros repetidos.','Selecione as colunas que definem duplicidade; decida qual ocorrência manter.','Registros distintos podem ter atributos iguais: valide a chave de negócio.','duplicatas'),
('String to Number / Number to String','Converte tipos entre texto e valores numéricos.','Selecione colunas; ajuste convenções de separador decimal; confira falhas.','Remova símbolos de moeda e espaços antes da conversão quando necessário.','tipos conversão'),
('String to Date&Time','Converte texto em datas e horários.','Informe o padrão correspondente à entrada; confira fuso e valores inválidos.','dd/MM/yyyy e MM/dd/yyyy têm significados diferentes.','datas'),
('String Manipulation','Limpa, combina ou extrai partes de textos.','Selecione a coluna; monte a expressão na configuração; escolha substituir ou criar coluna.','Confira espaços, acentos e diferenças de caixa antes de comparar categorias.','texto'),
('Math Formula','Calcula uma coluna numérica com uma expressão.','Escolha a fórmula; referencie colunas; crie uma coluna de saída com nome claro.','Proteja divisões por zero e confira valores ausentes.','fórmula cálculo'),
('Rule Engine','Cria uma coluna a partir de regras avaliadas de cima para baixo.','Escreva condições e resultados; termine com uma regra padrão TRUE.','A primeira regra verdadeira define o resultado.','regras if'),
('Column Rename / Column Resorter','Renomeia e reorganiza colunas.','Use nomes consistentes; posicione chaves, atributos e alvo em uma ordem compreensível.','Registre mudanças de nomes usadas por nós posteriores.','nomes'),
('Joiner','Combina tabelas por chaves.','Escolha chaves e tipo de junção: inner, left, right ou full outer; confira cardinalidade.','Chaves repetidas em ambas as tabelas podem multiplicar linhas.','join merge'),
('Concatenate','Empilha tabelas por linhas.','Confira nomes e tipos de coluna; defina como tratar colunas ausentes.','Empilhar linhas é diferente de juntar colunas por chave.','union'),
('GroupBy','Agrupa linhas e calcula agregações.','Defina chaves de grupo e operações como soma, média, contagem ou máximo.','Contagem de linhas e contagem de valores não ausentes podem diferir.','agregação'),
('Pivoting / Unpivoting','Transforma dados entre formato largo e longo.','Escolha identificadores, categorias e valores; defina agregação para o pivot.','Confira se combinações de chave e categoria são únicas.','pivot tabela'),
('Normalizer / Normalizer (Apply)','Escala atributos numéricos e reutiliza a transformação aprendida.','Ajuste no treino; aplique a mesma transformação no teste; exclua o alvo.','KNN, SVM e métodos de distância são sensíveis à escala.','normalização zscore minmax'),
('One to Many','Converte categorias em colunas indicadoras.','Selecione colunas categóricas; aplique um esquema consistente entre treino e produção.','Categorias novas no teste exigem tratamento definido.','one hot encoding'),
('Numeric Outliers','Identifica ou trata valores numéricos extremos.','Selecione colunas; examine limites e estratégia de tratamento.','Um extremo pode ser um evento real; não remova sem critério de domínio.','outlier IQR'),
('Sorter / Rank','Ordena registros ou atribui posições.','Escolha colunas e sentido; defina desempates quando necessário.','Ordene por data antes de criar atributos temporais.','ordenação ranking')])
batch('Exploração e gráficos',[
('Statistics','Resume distribuição e qualidade dos atributos.','Examine mínimos, máximos, médias, dispersão e faltantes por coluna.','Estatística global pode ocultar diferenças entre grupos.','descritiva'),
('Histogram','Mostra a distribuição de uma variável numérica.','Escolha coluna e número de intervalos; observe assimetria e valores extremos.','Compare distribuições de treino e teste para detectar mudanças.','distribuição'),
('Scatter Plot','Explora a relação entre duas variáveis.','Selecione eixos; use cor por classe quando disponível.','Correlação visual não demonstra causalidade.','dispersão'),
('Box Plot','Compara dispersão e mediana entre grupos.','Escolha variável numérica e categoria de agrupamento.','Pontos extremos merecem investigação, não exclusão automática.','boxplot'),
('Bar Chart / Line Plot','Compara categorias ou mostra evolução ordenada.','Agregue os dados; use barras para categorias e linha para séries ordenadas.','Para tempo, ordene datas e confira a frequência das observações.','gráfico'),
('Linear Correlation','Calcula correlação linear entre colunas numéricas.','Selecione atributos; examine pares redundantes e relações com o alvo.','Correlação baixa não exclui relações não lineares.','pearson'),
('Data Explorer / Table View','Inspeciona dados e padrões de qualidade.','Confira amostras, tipos, cardinalidade, distribuição e faltantes.','Visualizações e nomes podem depender da extensão e versão instalada.','explorar dashboard')])
batch('Machine learning',[
('Learner → Predictor','O Learner aprende um modelo; o Predictor o aplica a novas linhas.','Conecte treino ao Learner; conecte modelo e tabela de teste ao Predictor; avalie previsões.','A tabela de teste precisa ter atributos compatíveis com o treino.','modelo'),
('Decision Tree Learner / Predictor','Classifica com regras de divisão em árvore.','Selecione alvo categórico; ajuste profundidade ou tamanho mínimo de nós quando disponíveis.','Árvores profundas podem memorizar os exemplos de treino.','árvore classificação'),
('Random Forest Learner / Predictor','Combina árvores para classificação ou regressão, conforme o nó escolhido.','Escolha a variante adequada; configure número de árvores, amostragem e semente.','Compare com um modelo simples e avalie fora do treino.','floresta ensemble'),
('Logistic Regression Learner / Predictor','Estima probabilidades de classes em classificação.','Defina alvo; codifique categorias conforme o nó; examine regularização e probabilidades.','O nome inclui regressão, mas seu uso típico aqui é classificação.','logística'),
('Naive Bayes Learner / Predictor','Classificador probabilístico com hipótese de independência condicional.','Escolha alvo e atributos compatíveis; treine; avalie por classe.','A hipótese simplifica o problema; a qualidade deve ser medida empiricamente.','bayes'),
('K Nearest Neighbor','Classifica a partir de exemplos próximos.','Selecione alvo e k; normalize atributos; escolha distância quando disponível.','k pequeno aumenta sensibilidade a ruído; k grande suaviza decisões.','KNN vizinhos'),
('SVM Learner / Predictor','Aprende uma fronteira de decisão controlada por kernel e regularização.','Normalize atributos; escolha kernel e parâmetros; ajuste por validação.','Escala e configuração afetam fortemente o resultado.','support vector'),
('Linear Regression Learner / Regression Predictor','Prevê um alvo numérico por uma combinação dos atributos.','Escolha alvo contínuo; trate categorias; avalie resíduos e métricas no teste.','Examine colinearidade e relações que o modelo linear não representa.','regressão'),
('Gradient Boosted Trees','Combina árvores sequencialmente para melhorar previsões.','Escolha nós de classificação ou regressão; ajuste árvores, profundidade e learning rate.','Use validação para controlar complexidade e overfitting.','boosting'),
('Desbalanceamento de classes','Classes raras podem ser ignoradas por um modelo com alta acurácia.','Inspecione proporções; avalie precision, recall e F1 por classe; ajuste pesos ou reamostragem.','Reamostragem pertence ao treino, dentro de cada fold de validação.','SMOTE imbalance'),
('Seleção de atributos','Reduz atributos irrelevantes e redundantes.','Comece com critérios de domínio; compare desempenho e estabilidade usando validação.','Selecionar atributos com toda a base antes da avaliação também causa vazamento.','features'),
('Persistência do modelo','Guarda modelos e transformações para inferência posterior.','Use portas e writers compatíveis; salve junto o pré-processamento e o esquema de atributos.','PMML não suporta todos os modelos; confira compatibilidade antes de exportar.','PMML model writer')])
batch('Validação e métricas',[
('Partitioning','Separa dados em treino e teste.','Exemplo: 70% treino e 30% teste; fixe semente; use estratificação para classes quando apropriado.','Em séries temporais, preserve a ordem e não embaralhe o futuro com o passado.','split 70 30'),
('X-Partitioner / X-Aggregator','Organiza validação cruzada por folds.','Configure k folds; execute treinamento e previsão dentro do loop; reúna previsões e avalie.','Ajuste imputação, normalização e PCA novamente no treino de cada fold.','cross validation'),
('Scorer','Compara classe real e prevista.','Selecione coluna real e coluna predita; examine matriz de confusão e métricas por classe.','Acurácia sozinha é insuficiente em bases desbalanceadas.','classificação'),
('Precision, Recall e F1','Precision mede a confiabilidade dos positivos; recall mede cobertura dos positivos reais.','Precision = TP/(TP+FP); Recall = TP/(TP+FN); F1 = 2PR/(P+R).','Declare a classe positiva e como são tratadas divisões por zero.','métricas'),
('Matriz de confusão','Cruza rótulos reais e previsões por classe.','Identifique TP, TN, FP e FN a partir dos rótulos; observe onde o modelo mais erra.','Confirme a orientação dos eixos antes de interpretar as células.','confusion matrix'),
('ROC Curve / AUC','Avalia a ordenação de probabilidades ao variar o limiar de classificação.','Use probabilidades para a classe positiva; compare AUC e pontos de operação.','Em classes muito raras, complemente com curva precision-recall.','roc auc'),
('Numeric Scorer','Avalia previsões numéricas.','Selecione valor real e previsto; compare MAE, RMSE e R² quando disponíveis.','MAE e RMSE têm a unidade do alvo; RMSE penaliza mais erros grandes.','regressão'),
('R² e baseline','R² mede ajuste relativo a uma referência baseada na média.','Compare com previsão simples; inspecione erros por segmento e amplitude do alvo.','R² pode ser negativo em dados de teste.','baseline'),
('Parameter Optimization Loop','Busca combinações de hiperparâmetros.','Defina espaço de busca; avalie cada combinação por validação; escolha a métrica adequada.','Reserve o teste final; não o use para escolher parâmetros.','otimização grid search'),
('Data leakage','Ocorre quando informações indisponíveis na previsão chegam ao treinamento ou à seleção.','Separe treino e teste antes de ajustar transformações; remova proxies do alvo; respeite grupos e datas.','Normalizar treino e teste separadamente também cria transformações incompatíveis.','vazamento'),
('Validação temporal','Simula previsão de observações futuras.','Treine no passado; valide em um intervalo posterior; avance as janelas conforme o cenário.','Features devem usar apenas informações disponíveis no instante da previsão.','time series walk forward'),
('Overfitting / Underfitting','Overfitting: boa memorização e baixa generalização. Underfitting: modelo pouco expressivo.','Compare resultados de treino e validação; ajuste complexidade, atributos e regularização.','Compare modelos sob a mesma divisão e a mesma métrica.','generalização')])
batch('PCA e clustering',[
('PCA Compute / PCA Apply','Aprende uma projeção e transforma atributos em componentes principais.','Use atributos numéricos; trate faltantes; ajuste escala no treino; aprenda PCA no treino e aplique ao teste.','Não inclua a coluna alvo no PCA.','redução dimensionalidade'),
('Variância explicada','Indica quanta variabilidade os componentes preservam.','Escolha componentes por variância acumulada e valide o efeito no objetivo final.','Preservar 95% é uma referência possível, não uma regra universal.','componentes'),
('K-Means','Agrupa exemplos por proximidade a centroides.','Normalize atributos; escolha k; fixe semente; inspecione grupos e perfis.','Não use códigos numéricos de categorias como distâncias sem justificativa.','clusters'),
('DBSCAN','Agrupa regiões densas e identifica ruído.','Escolha distância, raio de vizinhança e mínimo de pontos conforme implementação.','A escala dos atributos muda a noção de vizinhança.','densidade'),
('Hierarchical Clustering','Organiza agrupamentos em uma hierarquia.','Escolha distância e ligação; examine o dendrograma e um ponto de corte.','Custo de memória pode crescer muito com o número de linhas.','dendrograma'),
('t-SNE','Projeta dados para exploração visual de vizinhanças.','Normalize quando adequado; fixe semente; teste perplexidade e outros parâmetros disponíveis.','Distâncias globais e separação visual não comprovam classes reais.','visualização'),
('Silhouette e avaliação dos clusters','Compara coesão interna e separação entre grupos.','Use uma implementação compatível; complemente a métrica com análise de domínio.','Clusters precisam ser úteis e interpretáveis para o problema.','silhueta')])
batch('Automação',[
('Table Row to Variable Loop Start','Processa parâmetros de uma tabela linha a linha.','Converta cada linha em variáveis; controle nós internos; use um Loop End compatível.','Tipos das variáveis e configurações dos nós precisam coincidir.','loop'),
('Chunk Loop Start','Processa uma tabela em blocos.','Defina tamanho do bloco; execute transformação; reúna resultados no fim do loop.','Agregações globais podem exigir uma etapa posterior à reunião dos blocos.','lotes'),
('Group Loop Start','Executa etapas para cada grupo.','Selecione chaves de agrupamento; processe cada grupo; consolide saídas.','Grupos com poucas observações podem inviabilizar certos modelos.','grupo'),
('IF Switch / CASE Switch','Escolhe caminhos condicionais no workflow.','Crie uma condição ou variável; selecione o ramo ativo; una saídas com nós compatíveis.','Confira o comportamento de ramos inativos e tipos das portas.','condicional'),
('Try / Catch','Permite tratar falhas previstas dentro do fluxo.','Delimite uma etapa sujeita a erro; defina alternativa; registre o motivo da falha.','Não silencie erros sem guardar diagnóstico.','erros'),
('Caminhos portáveis','Facilita mover workflows entre computadores.','Use referências relativas ao workflow e recursos compartilhados quando suportado.','Evite caminhos absolutos pessoais em um fluxo que será distribuído.','path'),
('Reprodutibilidade','Permite repetir o experimento com condições conhecidas.','Registre versão, extensões, origem dos dados, sementes e parâmetros.','Uma semente fixa não garante igualdade entre versões ou bibliotecas diferentes.','semente')])
batch('Python e SQL',[
('Python Script','Integra bibliotecas Python ao workflow.','Instale KNIME Python Integration; selecione ambiente com as bibliotecas; leia entrada e escreva saída pela API knime.scripting.io.','Os exemplos aqui usam a integração atual, não a antiga API de Python.','pandas script'),
('Python View','Produz uma visualização Python no KNIME.','Prepare dados; crie uma figura ou saída suportada; associe à saída de view da API.','Confira bibliotecas e formatos aceitos pela versão instalada.','matplotlib'),
('Ambiente Python','Define intérprete e dependências usadas pelo nó.','Use o ambiente fornecido quando suficiente ou configure um ambiente personalizado na integração.','Biblioteca instalada em outro Python não fica automaticamente disponível no KNIME.','conda'),
('DB Connector','Abre conexão com um banco de dados.','Escolha o connector apropriado; configure host, driver, banco e credenciais.','Use contas com permissões adequadas e não exponha senhas em anotações.','banco SQL'),
('DB Table Selector / DB Query Reader','Seleciona ou consulta dados de um banco.','Selecione tabela ou escreva SELECT; filtre na origem; leia apenas as colunas necessárias.','Use mecanismos seguros de parametrização ao incorporar entradas externas.','consulta'),
('DB nodes vs. table nodes','Nós DB permitem compor operações executadas no banco antes de trazer dados.','Filtre, agregue e una no banco quando apropriado; materialize resultados somente quando necessário.','Inspecione a consulta gerada e os custos no banco.','pushdown')])
batch('IA generativa',[
('KNIME AI Extension','Adiciona nós para LLMs, embeddings, RAG e agentes.','Instale a extensão; escolha provedor e modelos disponíveis; configure autenticação; teste com poucas linhas.','Nós e disponibilidade de provedores variam por versão; consulte o guia oficial.','LLM instalação'),
('Prompt e saída estruturada','Um prompt define tarefa, contexto, restrições e formato de resposta.','Declare objetivo; delimite dados; forneça exemplo; solicite estrutura; valide a saída antes de usá-la.','Saída de LLM pode conter erros mesmo quando parece bem formatada.','prompt JSON'),
('Embeddings','Representam textos como vetores para busca por similaridade.','Selecione modelo; gere embeddings de documentos; use o mesmo modelo para consultas.','Vetores de modelos diferentes não devem ser misturados na mesma comparação.','vetores'),
('RAG','Combina recuperação de documentos com geração de resposta.','Divida documentos; gere embeddings; indexe; recupere trechos; envie contexto e pergunta ao LLM.','Peça referências e verifique se elas realmente sustentam a resposta.','retrieval'),
('Agentes de IA','Permitem que um modelo escolha ferramentas para cumprir uma tarefa.','Defina ferramentas e permissões; limite iterações; registre ações; teste falhas e entradas adversas.','Ações com efeito externo precisam de controles proporcionais ao impacto.','agent'),
('Avaliação de LLMs','Mede qualidade, aderência e comportamento em um conjunto de casos.','Prepare perguntas e respostas esperadas; avalie fundamentação, formato, custo e latência.','Reavalie ao mudar modelo, prompt ou documentos.','avaliação'),
('Credenciais e custos','Integrações podem enviar dados a serviços e consumir APIs cobradas.','Configure credenciais com mecanismos próprios; estime volume, tokens e tentativas; monitore erros.','Confira as políticas do provedor antes de enviar dados sensíveis.','tokens privacidade')])
batch('Receitas',[
('Classificação · Iris','Um fluxo inicial para prever espécie a partir de medidas.','CSV Reader → Column Filter → Partitioning estratificado → Decision Tree Learner → Decision Tree Predictor → Scorer.','Conecte ao Predictor tanto o modelo do Learner quanto a tabela de teste.','iris classificação'),
('Comparar modelos · Heart','Compara árvore, Random Forest e Naive Bayes de forma consistente.','Leitura → divisão estratificada → pré-processamento ajustado no treino → três Learners → Predictors no mesmo teste → Scorer por modelo.','Compare F1 e recall da classe de interesse; use validação para seleção.','heart breast cancer'),
('Com PCA vs. sem PCA','Avalia se a redução dimensional ajuda o classificador.','Use a mesma divisão; ramo A: preparação → modelo; ramo B: preparação → PCA Compute/Apply → modelo; compare métricas.','PCA deve ser aprendido só no treino e aplicado com o mesmo modelo ao teste.','PCA random forest comparação'),
('Regressão · preços','Prevê um valor contínuo e examina o erro.','Reader → Partitioning → preparação → Linear Regression Learner → Regression Predictor → Numeric Scorer.','Compare com baseline e observe erros em diferentes faixas do preço.','carros vendas'),
('Segmentação de clientes','Cria grupos com perfis de comportamento.','Reader → GroupBy por cliente → seleção de atributos → Missing Value → Normalizer → K-Means → gráficos por cluster.','Remova identificadores dos atributos de distância e descreva cada grupo.','clientes'),
('Vendas por mês','Resume faturamento e evolução temporal.','Reader → String to Date&Time → extração de mês/ano → GroupBy → Sorter → Line Plot → Excel Writer.','Use ano e mês juntos para não misturar meses de anos diferentes.','vendas financeiro'),
('Validação cruzada','Estima desempenho em múltiplas divisões da base de treino.','X-Partitioner → ajuste de preparação no fold de treino → Learner → aplicação ao fold de validação → Predictor → X-Aggregator → avaliação.','Guarde um teste final intocado; adapte portas e agregação à família de nós usada.','k folds'),
('RAG · documentos','Consulta uma coleção de textos com apoio de LLM.','Leitura dos documentos → divisão em trechos → embeddings → armazenamento vetorial → recuperação → prompt com contexto → LLM → validação.','É um roteiro conceitual; conectores e nomes dependem da extensão e do provedor.','rag FAQ')])
batch('Solução de problemas',[
('Coluna não aparece','O nó pode exigir um tipo específico ou receber um esquema desatualizado.','Confira a tabela de entrada; execute nós anteriores; verifique tipos; reabra a configuração.','Converter tipos incorretamente pode introduzir valores ausentes.','erro schema'),
('Predictor falha','Modelo e tabela podem ter atributos incompatíveis.','Compare nomes, tipos e codificação; aplique as transformações do treino ao teste.','Salve o pipeline de preparação junto com o modelo.','modelo erro'),
('Workflow lento ou sem memória','Dados, junções ou loops podem aumentar o volume processado.','Filtre cedo; remova colunas desnecessárias; confira cardinalidade de joins; use DB nodes e blocos quando adequado.','Aumentar memória não corrige uma junção que multiplicou linhas indevidamente.','performance'),
('Métrica boa demais','Pode haver vazamento, duplicatas ou avaliação no treino.','Confira origem do alvo; proxies; sobreposição de grupos; transformação antes do split; tabela recebida pelo Scorer.','Valide também com uma divisão coerente com o uso real.','leakage'),
('Nó não encontrado','O nome, extensão ou disponibilidade pode ter mudado.','Busque o nome em inglês no Hub; verifique instalação e compatibilidade; consulte a descrição atual.','Este guia é amplo, mas não substitui o catálogo completo de extensões.','extensões'),
('API ou Python falha','Pode faltar dependência, credencial ou compatibilidade de ambiente.','Leia a mensagem completa; valide ambiente; teste entrada pequena; confira autenticação e status da API.','Registre diagnóstico sem expor tokens ou senhas.','debug')])
(p/'dist/data.js').write_text('const ENTRIES = '+json.dumps(data,ensure_ascii=False)+';\nconst CATEGORIES = '+json.dumps(categories,ensure_ascii=False)+';',encoding='utf-8')
print(len(data),'entries')
